duplicate:
  default: false
  overrides:
    image: true
    video: true
    post: true
    notice: true


headers:
  User-Agent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_6_1 like Mac OS X) AppleWebKit/605.1.16 (KHTML, like Gecko) Mobile/15E148; iPhone18.6.1; iPhone17,2'


output_template:
  # '{date} {community_name} - {title} {source}.WEB-DL.{quality}.{video}.{audio}-{tag}'
  video: '{date}.{title}.{quality}.{community_name}.{artis}.{source}.WEB-DL.{video}.{audio}-{tag}'
  tag: 'slime'
  # Default File datetime
  date_formact: "%y%m%d"


Donwload_Dir_Name:
  download_dir: "Berriz downloads"
  # Default Folder formact
  dir_name: "{date} {community_name} {source} {artis} {title}"
  # Default Folder datetime
  date_formact: "%y%m%d_%H-%M_%S"


Container:
  # ffmpeg or mkvtoolnix
  mux: MKVTOOLNIX
  # [if choese mkvtoolnix enforce .mkv ts, mp4, mov, m4v, mkv, avi
  video: mp4
  # MP4DECRYPT, SHAKA_PACKAGER
  decryption-engine: shaka-packager


HLS or MPEG-SASH:
  # Download with MPEG-DASH or HLS but if content DRM protect will forced DASH-MPEG
  HLS: false


TimeZone:
  # UTC+8 utc+8 utc8 +8 8 -8 [timezone should be in -12 ~ +14]
  time: 8


KeyService:
  # mspr wv watora_wv cdrm_wv cdrm_mspr
  source: mspr


CDM:
  # WVD
  widevine: google_aosp_on_ia_emulator_14.0.0_13cea62a_4464_l3.wvd
  # LARLEY_PR
  playready: realtek_semiconductor_corp_coolnewdevice_xr-700_sl2000.prd


berriz:
  account: mrqi7@powerscrews.com
  password: jO2^Gopc7rkv


logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'