duplicate:
  default: false
  overrides:
    image: true
    video: true
    post: true
    notice: true


headers:
  Fake-User-Agent: true
  User-Agent: 'curl/7.64.1'


output_template:
  # '{date} {community_name} - {title} {artis}.WEB-DL.{quality}.{video}.{audio}-{tag}'
  video: '{date}.{title}.{quality}.{community_name}.{artis}.{source}.WEB-DL.{video}.{audio}-{tag}'
  tag: 'slime'
  # Default File datetime
  date_formact: "%y%m%d"


Donwload_Dir_Name:
  download_dir: "Berriz downloads"
  # Default Folder formact
  dir_name: "{date} {community_name} {source} {artis} {title}"
  # Default Folder datetime
  date_formact: "%y%m%d_%H-%M_%S"


Container:
  # ffmpeg or mkvtoolnix
  mux: ffmpeg
  # [if choese mkvtoolnix enforce .mkv ts, mp4, mov, m4v, mkv, avi
  video: mp4
  # MP4DECRYPT, SHAKA_PACKAGER
  decryption-engine: shaka-packager


HLS or MPEG-SASH:
  # Download with MPEG-DASH or HLS but if content DRM protect will forced DASH-MPEG
  HLS: false


TimeZone:
  # UTC+8 utc+8 utc8 +8 8 -8 [timezone should be in -12 ~ +14]
  time: 8


KeyService:
  # mspr wv watora_wv cdrm_wv cdrm_mspr
  source: mspr


CDM:
  # WVD
  widevine: google_aosp_on_ia_emulator_14.0.0_13cea62a_4464_l3.wvd
  # LARLEY_PR
  playready: realtek_semiconductor_corp_coolnewdevice_xr-700_sl2000.prd


berriz:
  # only support Berriz account no auth support (Google/Apple)
  account: mrqi7@powerscrews.com
  password: jO2^Gopc7rkv


logging:
  level: INFO
  # formact only show in log file not on console
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'


Proxy:
  Proxy_Enable: false
  # static\proxy\proxy.txt
  use_proxy_list: false
  # if not use_proxy_list than run this proxy
  use_proxy: http
  http: ['socks5://127.0.0.1:40000']
  https: ['http://104.17.35.217:80', 'socks4://122.54.193.69:8082' ]